import{useEffect,useState}from'react';import type{LabState,MarketSnapshot,Side}from'../shared/types';const API=import.meta.env.VITE_API_BASE||'http://localhost:8787';const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
type A={interval:string;signal:string;reason:string;rsi:number;atr:number;volumeRatio:number};type BT={interval:string;startingEquity:number;finalEquity:number;returnPct:number;maxDrawdownPct:number;trades:number;feePct:number;curve:{t:number;equity:number}[]};
export default function App(){const[m,setM]=useState<MarketSnapshot|null>(null),[s,setS]=useState<LabState|null>(null),[aa,setAa]=useState<A[]>([]),[suite,setSuite]=useState<BT[]>([]),[err,setErr]=useState('');
async function refresh(){try{const[x,y,z]=await Promise.all([fetch(API+'/api/market/BTCUSDT'),fetch(API+'/api/state'),fetch(API+'/api/multi-analysis/BTCUSDT')]);setM(await x.json());setS(await y.json());setAa(await z.json());setErr('')}catch{setErr('API unavailable — start the server')}}useEffect(()=>{refresh();const id=setInterval(refresh,10000);return()=>clearInterval(id)},[]);
async function session(action:'start'|'pause'){await fetch(API+'/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});refresh()}async function order(side:Side){if(!s)return;const notional=Math.min(10,s.equity*s.risk.maxPositionPct/100);const r=await fetch(API+'/api/paper/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({side,notional})});const x=await r.json();if(!r.ok)setErr(x.error);else setErr('');refresh()}async function runSuite(){const r=await fetch(API+'/api/backtest-suite/BTCUSDT');const x=await r.json();if(!r.ok)setErr(x.error);else{setSuite(x);setErr('')}}
const pts=(b:BT)=>{if(!b.curve?.length)return'';const ys=b.curve.map(x=>x.equity),min=Math.min(...ys),max=Math.max(...ys),span=max-min||1;return b.curve.map((x,i)=>`${i/(b.curve.length-1||1)*100},${100-(x.equity-min)/span*100}`).join(' ')};
return <main><header><div><span className="eyebrow">VOID LIGHT</span><h1>Trading Lab</h1></div><div className="pill">PAPER ONLY · RESEARCH MODE</div></header><section className="hero"><div><small>BTC / USDT</small><strong>{m?money(m.price):'—'}</strong><span className={m&&m.changePct>=0?'up':'down'}>{m?m.changePct.toFixed(2)+'% 24h':'Loading…'}</span></div><div className="session"><button onClick={()=>session('start')}>Start session</button><button className="ghost" onClick={()=>session('pause')}>Pause</button></div></section>{err&&<div className="error">{err}</div>}
<section className="grid">{[['Equity',s?money(s.equity):'—'],['Cash',s?money(s.cash):'—'],['BTC',s?s.asset.toFixed(6):'—'],['Daily P&L',s?money(s.dailyPnl):'—'],['Status',s?.status||'—'],['Trades',String(s?.trades.length??0)]].map(([x,y])=><article key={x}><small>{x}</small><b>{y}</b></article>)}</section>
<h2 className="sectionTitle">Multi-timeframe scanner</h2><section className="scanner">{aa.map(a=><article key={a.interval}><div><span className="tf">{a.interval}</span><b className={a.signal==='BULLISH'?'up':a.signal==='BEARISH'?'down':''}>{a.signal}</b></div><p>{a.reason}</p><div className="metrics"><span>RSI <b>{a.rsi.toFixed(1)}</b></span><span>ATR <b>{a.atr.toFixed(1)}</b></span><span>VOL <b>{a.volumeRatio.toFixed(2)}x</b></span></div></article>)}</section>
<section className="panel"><div><h2>Strategy Comparison</h2><p>Same deterministic EMA/RSI filter across 15m, 1h and 4h. Includes simulated 0.1% fee.</p></div><button onClick={runSuite}>Run comparison</button></section>
{suite.length>0&&<section className="scanner">{suite.map(b=><article key={b.interval}><div><span className="tf">{b.interval}</span><b className={b.returnPct>=0?'up':'down'}>{b.returnPct.toFixed(2)}%</b></div><svg className="spark" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts(b)} fill="none" stroke="currentColor" strokeWidth="2"/></svg><div className="metrics"><span>Final <b>{money(b.finalEquity)}</b></span><span>DD <b>{b.maxDrawdownPct.toFixed(2)}%</b></span><span>Trades <b>{b.trades}</b></span></div></article>)}</section>}
<section className="panel"><div><h2>Risk Guard</h2><p>Deterministic veto layer; strategy signals cannot bypass it.</p></div><div className="rules">{s&&<><span>Profit stop <b>+{s.risk.dailyProfitTargetPct}%</b></span><span>Loss stop <b>-{s.risk.dailyLossLimitPct}%</b></span><span>Max trades <b>{s.risk.maxTradesPerDay}</b></span><span>Max position <b>{s.risk.maxPositionPct}%</b></span></>}</div></section>
<section className="panel"><div><h2>Manual Paper Execution</h2><p>$10 paper orders through the same Risk Engine. No exchange credentials.</p></div><div className="session"><button disabled={s?.status!=='RUNNING'} onClick={()=>order('BUY')}>Paper Buy $10</button><button disabled={s?.status!=='RUNNING'||!s?.asset} className="ghost" onClick={()=>order('SELL')}>Paper Sell $10</button></div></section>
<section className="panel trades"><h2>Forward-test Journal</h2>{!s?.trades.length?<p>No paper trades yet.</p>:s.trades.map(t=><div className="trade" key={t.id}><b className={t.side==='BUY'?'up':'down'}>{t.side}</b><span>{money(t.notional)} @ {money(t.price)}</span><small>{new Date(t.createdAt).toLocaleString()}</small></div>)}</section><footer>Binance public data · EMA/RSI/ATR/volume research · paper execution · v0.3</footer></main>}